version: "3.8"
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: django-rest
    volumes:
      - .:/django-rest
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=snippets
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - .postgres
    labels:
      description: Postgresql Database
      service: postgresql
    ports:
      - "5433:5432"
volumes:
  postgres_data:
