version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django-rest
    volumes:
      - .:/django-rest
    ports:
      - "8000:8000"
  postgres:
    image: 'postgres:15.2'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default
    ports:
      - '5432:5432'
    volumes:
      - .:/var/lib/postgresql/data/
    labels:
      description: "Postgresql Database"
      service: "postgresql"